version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5433:5432"
    volumes:
      - habit:/var/lib/postgresql

volumes:
  habit:
    external: true